### PR TITLE
Fix bmm parsing

### PR DESCRIPTION
**Pull request by pieterbos**
Spent a few hours on fixing bmm parsing: 

- [x] fix bmm parsing so that it actually parsed CIMI
- [x] fix ReferenceModelAccessTest
- [x] replace included compiled antlr grammar with the actual antlr one
- [x] move ANTLR error classes to base package.
- [x] correctly parse the horizontal comment line, both for template_overlays and normal comments in BMM, by parsing it in the lexer.
- [x] actually listen for antlr parser errors and throw exception (at least for now) in the odinLoadImpl.
- [x] add test that parses all reference-models
- [x] make the ReferenceModelAccess parse directories recursively
- [x] fix some errors with optional attributes
- [x] make parsing/validating test work on _all_ bmm reference-models

The HL7 fihr model in the reference-models repo is missing the Signature type, so it does not validate.
The task-planning BMM has some duplicate classes in the packages section. I removed the duplicates, so now it parses and seems to validate.

### CODE REVIEW

**Comment by wolandscat** [comment]
Interesting - I had to add more checking logic to the ADL Workbench just now to handle the current CIMI schema, which contains mistakes it did not catch (generic properties with wrong number of generic parameters).

**Comment by pieterbos** [comment]
It’s very possible the BMM still has mistakes it doesn’t yet catch. It’s also possible the included CIMI grammar has fixes already included, @cnanjo added it before.
The BMM code seems to be a very direct port from the Eiffel BMM code. All I did was fix some small mistakes that were incorrectly ported from the Eiffel code so that it parses CIMI and does not log any errors. The content has not yet been tested, nor have I done a full review of the code.
The next steps would be to add a test that parses all BMM reference models, then step by step integrate it into the archetype validator and flattener, each step running the validator and flattener tests to validate the implementation.

**Comment by pieterbos** [comment]
So parsing all bmm models doesn't work. Got the basic parsing to work, fails on validation. Probably a number of issues that need fixing in the BMM implementation.

**Comment by pieterbos** [comment]
@wolandscat how do you determine which bmm_model to use for an archetype in the ADL workbench? I can't seem to find the code, and the bmm methods don't seem to have a clear answer to that question that includes version information. Or is selecting the right version a manual step?

**Comment by pieterbos** [comment]
hmm, seems to be an omission in some merge methods explaining why it is difficult to do :) But still doesn't answer how to handle different RM versions

**Comment by cnanjo** [comment]
Hi Pieter,

Did not realize that you were working on the BMM. I am aware of the issues and have code to check in. We might get a merge conflict.

Claude

**Comment by pieterbos** [comment]
Hi Claude,

Ah, sorry. Good thing we're on a separate branch :). I just wanted to see what the state is of the code and how much work it will be to fix, so I wrote some tests and some fixes to get a feel for it. I'll stop and wait for your code then.

**Comment by wolandscat** [comment]
@pieterbos see this code - https://github.com/wolandscat/EOMF/blob/a4983c666b98ed6de192b8c3ec0a88246dc48d7a/library/bmm/interface/reference_model_access.e#L114
that's a HashMap to convert the RM part of an archetype id to a ref to the actual RM (i.e. BMM).

**Comment by pieterbos** [comment]
@wolandscat how do you handle multiple versions of the same RM, for example the openEHR-EHR version 1.0.2, 1.0.3 and 1.0.4?

**Comment by pieterbos** [comment]
@cnanjo I also found some more issues that I had partially fixed locally, but not pushed:

- persistedBmmSchema.merge populates packages, it should populate canonical packages instead and not touch packages
- persistedpackage.merge can lead to duplicates in the classes list
- once you do populate canonicalPackages, validations trigger about missing definitions of the Any class.

**Comment by cnanjo** [comment]
Hi Pieter, 

No worries and let's definitely not throw your changes away. Let me do a pull request and then we reconcile at least to what I have so far. Then let's divide and conquer.

Claude.

**Comment by pieterbos** [comment]
Divide and conquer sounds good.

**Comment by cnanjo** [comment]
Pieter,

I am okay with the three pull requests thus far. I left the merge to you. I
will be back online this week so I can do some OpenEHR coding work.

Pieter and Thomas,

I may need a JSON and XML serialization of the BMM for work I am doing in
CIMI. Are there schemas/conventions for these non-bmm serializations?

Thank you

**Comment by pieterbos** [comment]
@cnanjo for JSON, check JacksonUtil in the archie-utils package. That pretty much outputs JSON following the conventions others use as well for OpenEHR, I think more or less the same as in the REST-api. If you configure that you can also output json schemas easily. It's configure to output type markers as well, but mainly for everything extending OpenEHRBase.

To serialize, something along the lines of:
```
JacksonUtil.getObjectMapper().writeValueAsString(persistedBmmSchema);
```

you would need to mark all transient fields as transient to do this, or with @JsonIgnore (they are transient in the eiffel code as well). Plus probably the current dependency tree may mean you cannot directly use that jacksonutil in the BMM package.

To deserialize you need to do slightly more work.

You will get a very direct representation of the P_BMM model in JSON.

**Comment by pieterbos** [comment]
There's not a lot of ADL changes in here - just the fix to parse the '-------------' lines correctly. This is done by matching the following input as one token instead of two plus whitespace:

```
-------------------
<optional whitespace or newlines>
template_overlay
```

And matching just '-----------' without the template_overlay as a separate comment token. ANTLR will match the longest token first, so the template overlay plus horizontal line will always get priority over just a comment. It removes the need to use ```-- -----------``` as a comment markup line in the BMM files.

**Pull request merged**
