### PR TITLE
Fix apgar test

### PR DESCRIPTION
**Pull request by pieterbos**
Fix the apgar CKM archetype validation. It failed because term_bindings used a path that needed a C_COMPLEX_OBJECT_PROXY (use_node) to be replaced before being valid. I changed it in AOMPathQuery, but put it behind a boolean flag for now. Probably this needs to be generic behaviour for at least ```archetype.hasPath(String path)```, perhaps also itemAtPath and itemsAtPath. 
Doing that in all cases will make a few tests fail, but those are easily fixed.

I cannot find the behaviour in the ADL workbench code in this case. Maybe @wolandscat can explain what it should do? :)

### CODE REVIEW

**Comment by wolandscat** [comment]
You might want to [look here](https://github.com/openEHR/adl-tools/blob/bdd9d68822d56af6bc9a65d2148db2c1f50c1ab2/components/adl_compiler/src/comparator/archetype_flattener.e#L111). This is where proxy objects get converted to their real equivalents so that flattening will work properly.

**Comment by pieterbos** [comment]
Thanks for the link Thomas. But converting c_complex_object_proxies works fine in archie and doesn't need a fix.

The question is in the validation of VTTBK. The CKM archetype of the Apgar index has some term_bindings that do a use_node. It has two things that go wrong, both of which are fixed in this pull request. The question is if it should be like this, or if the validation should just fail. The two things are:

1. In this pull request, the archetype queries for VTTBK now expands the c_complex_object_proxy  in memory without actually replacing it in the archetype. This means it effectitvely can query substructures of the c_complex_object_proxy even if has not yet been flattened. It's now only for this specific validation, but it could be for every aom path query.
2. In this pull request, if it encounters a c_complex_object_proxy in the path query lookup, it matches two ids: the id of the proxy and the id of the referred object. This changes the path query lookup implementation to match both ids instead of just the id of the proxy object.

So the question is mainly, should this just fail to validate, or should these changes be merged?

**Comment by wolandscat** [comment]
With respect to #2 above, the rules for proxy object paths is [given here](https://www.openehr.org/releases/AM/latest/docs/ADL2/ADL2.html#_paths_and_proxy_objects).

But I'm not quite clear on the original problem. Apgar in CKM is an ADL 1.4 archetype, and has to be converted to ADL2, which is a non-trivial transform. The ADL Workbench does this [here](https://github.com/openEHR/adl-tools/blob/master/components/adl_compiler/src/validator/aom_151_converter.e).

So we would need to be talking about the ADL2 result of that conversion, I assume - or did I just miss something?

**Comment by pieterbos** [comment]
yes, the ADL2 result of the conversion. I'll check the code, thanks.

**Pull request closed without merging**
