### PR TITLE
Add support for the conversion of in-memory classes to their persisted forms

### PR DESCRIPTION
**Pull request by cnanjo**
This is the first installment of functionality to support going from Bmm classes to PersistedBmm classes.

### CODE REVIEW

**Comment by pieterbos** [comment]
Thanks for the pull request! I'll review it next monday.

**Comment by cnanjo** [comment]
Hi Pieter,

Yes, definitely. And a few more changes.

Thanks a lot.

Claude

**Comment by pieterbos** [comment]
Then I guess I'll wait a bit before I merge it? Or you can merge it after review of course.

If you need it merged and/or a release, just say so.

**Comment by cnanjo** [comment]
I really should add the tests so let me add them and resubmit the pull request. I will need it in a release some time soon but it is not urgent right now.

**Comment by pieterbos** [comment]
Closing this PR since the corresponding P_BMM implementation has been migrated to a new approach. This could still be useful functionality, but written in a different way.

**Pull request closed without merging**
